#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

pre-deploy-script() {
    local APP="$1"; verify_app_name "$APP"
    local SCRIPT_PATH="$DOKKU_ROOT/$APP/predeploy.sh"

    dokku_log_info1 "Checking for pre deploy script..."

    if [[ ! -f "$SCRIPT_PATH" ]]; then
        dokku_log_info1 "No pre deploy script found."
        return 0
    fi

    dokku_log_info1 "Executing pre deploy script..."
    local OUTPUT=$(source "$SCRIPT_PATH")
    dokku_log_verbose_quiet "$OUTPUT"
}

post-deploy-script() {
    local APP="$1"; verify_app_name "$APP"
    local SCRIPT_PATH="$DOKKU_ROOT/$APP/postdeploy.sh"

    dokku_log_info1 "Checking for post deploy script..."

    if [[ ! -f "$SCRIPT_PATH" ]]; then
        dokku_log_info1 "No post deploy script found."
        return 0
    fi

    dokku_log_info1 "Executing post deploy script..."
    local OUTPUT=$(source "$SCRIPT_PATH")
    dokku_log_verbose_quiet "$OUTPUT"
}

post-deploy-script "$@"
